
BIN	:=	Strategie

SRCS	:=	src/JapExpo.c \
            src/carte_strategie.c \
            src/i2c_m.c \
            src/i2c_moteurs.c \
            src/i2c_servo.c \
            src/WMP.c \
            src/cmucam.c \
            src/WCC.c


## Information concernant le compilateur
include ../build/commun.mk
## À modifier si le fichier est utilisé sur un autre pc

