BIN	:=	ProtoCD

SRCS	:=	src/servo.c \
			src/protoCD.c\
			src/carte_servo.c \
			src/temps.c \
			src/i2c_s.c

## Information concernant le compilateur
include ../../build/commun.mk
## À modifier si le fichier est utilisé sur un autre pc

