BIN	:=	ProtoCD

SRCS	:=	src/servo.c \
			src/protoCD.c\
			src/carte_servo.c

## Information concernant le compilateur
include ../../build/commun.mk
## À modifier si le fichier est utilisé sur un autre pc

