enum etat_asser_t {
	AVANCE_DROIT_INIT=0,
	AVANCE_DROIT=2,
	AVANCE_DROIT_TEMPO,
	TOURNE_INIT,
	TOURNE_TEMPO,
	TOURNE,
	FIN_TOURNE,
	TOURNE_VERS_AVANCE,
	TOURNE_VERS_AVANCE_2,
	AVANCE_VERS_TOURNE,
	FIN_ASSER
};

extern char asser_actif;
