


enum etat_bras_t {
	E_BRAS_INIT=0,
	E_BRAS_BAS_OUVERT=1,
	E_BRAS_ATTENTE_PIECE=2,
	E_BRAS_BAS_FERME=3,
	E_BRAS_HAUT_FERME,
	E_BRAS_HAUT_LACHE,
	E_BRAS_HAUT_RESSERRE,
	E_BRAS_DEPOSE_FERME,
	E_BRAS_DEPOSE_OUVERT,
	E_BRAS_ATTENTE_PLEIN
} etat_bras_gauche,etat_bras_droit;
