BIN	:=	R11_Moteurs

SRCS	:=	src/R11_Moteurs.c \
            src/carte_moteurs.c \
            src/PaP.c \
            src/i2c_s.c \
            src/M_prop.c \
            src/temps.c \
            src/CapteurSonic.c 


## Information concernant le compilateur
include ../build/commun.mk
## À modifier si le fichier est utilisé sur un autre pc

