BIN	:=	BrasRobot

SRCS	:=	R12_Bras.c \
			servo/servo.c \
			moteurs/moteurs.c \
			temps/temps.c
			

## Information concernant le compilateur
include ../build/commun.mk
## À modifier si le fichier est utilisé sur un autre pc

