BIN	:=	BrasRobot

SRCS	:=	src/R12_Bras.c \
			src/servo.c \
			src/moteurs.c \
			src/temps.c
			

## Information concernant le compilateur
include ../build/commun.mk
## À modifier si le fichier est utilisé sur un autre pc

